---
# Este manual despliega toda la pila de aplicaciones en este sitio.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - common

- name: configure and deploy the webservers and application code
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: all
  remote_user: ansible
  become: yes

  roles:
    - db